version: 0.1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "0.1.0"
  assembly_file_version: "{version}"
  assembly_informational_version: "0.1.0-pre{build}"

platform: Any CPU

configuration: Release

install:
  - cmd: tools\NuGet\NuGet.exe restore Ichnaea.sln

build:
  project: Ichnaea.sln
  verbosity: normal
  publish_nuget: true

deploy:
  provider: Environment
  name: NuGet Staging
